FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update -y && \
    apt upgrade -y && \
    apt install npm -y && \
    npm install -g vue

RUN mkdir /home/pvm
RUN mkdir /home/pvm/frontend